#!/usr/bin/env node
'use strict';

const program = require('commander');
const config = require('./package.json');
const graticule = require('./');

program
.version(config.version)
.option('-i, --interval <n>', 'Interval of graticules')
.parse(process.argv);

console.log(JSON.stringify(graticule(program.interval)));
