#!/usr/bin/env node
'use strict';

const program = require('commander');
const config = require('./package.json');
const graticule = require('./');

program
.version(config.version)
.option('-i, --interval <n>', 'Interval of graticules')
.option('-n, --newlines', 'Use newline-delimited format for output')
.parse(process.argv);

const geojson = graticule(program.interval);
const output = program.newlines ? geojson.features.map(JSON.stringify).join('\n') : JSON.stringify(geojson);

console.log(output);
